import EvmSpecsVerify.Relations.State

/-!
# Assumptions ledger

Every assumption class used by the equivalence theorems, per the comparison
methodology. For each: why required, who guarantees it, whether a reachable
EVM state can violate it, and whether it is eliminable by proving.

## Fork / configuration

* `AmsterdamProfile` (Relations/State.lean) — the comparison is pinned to
  the Amsterdam configuration; SpecRef is structurally Amsterdam, the
  extraction is fork-parameterized via the `k_execution_profile` register.
  Threaded hypothesis, part of the intended statement; not eliminable.

## Representation invariants

* `StackRel.wf` — every stack entry `< 2^256`. An EVM invariant: SpecRef
  re-establishes it in each handler by wrapping (never states it); the
  extraction maintains it by `u256` reduction. Violations are unreachable
  from valid initial states; eliminable in principle by proving it
  invariant under all handlers (future work, tracked by the registry).
* `StackRel.frame`/`height` — the cursor reads as the height and the
  active frame's cursor-prefix represents the stack. Guaranteed by the
  host contract's reference reading (HostAxioms.lean:1845); established
  at frame entry (`stack_reset`) and preserved by the step lemmas.
* `StepRel` register hypotheses (`profile`, `message`, gas registers) —
  registers present in the register file. Guaranteed by `sail_model_init`
  + the interpreter's write discipline.

## Gas budget (memory family)

* `MemGasSafe` (Relations/Memory.lean) — the frame's live gas plus the cost
  already sunk into memory stays below `mem_cost (2^27)` ≈ `3.5 × 10^13`,
  the point where the extraction's u32 memory space could be exhausted
  (mismatch ledger MM-6: `memory_access` spec-aborts there, SpecRef extends).
  Real block gas limits are ~8 orders of magnitude smaller, so every real
  execution satisfies it. Threaded hypothesis on the memory-family step
  theorems; eliminable only by bounding `g` globally (frame-entry invariant),
  future work.

## Deliberate scope restrictions (this tranche)

* SpecRef dispatch (`opImplementation`) is `partial` — theorems target the
  handler `def`s directly (mismatch ledger MM-3). Lifts if upstream
  de-partials the interpreter block.
* The `mem` slice is a pass-through for the ALU family; memory content is
  not yet related (matrix row: unrelated).
* Precompiles, hashing, world state: out of scope; `n/a` rows in the
  coverage matrix.

## External trust

* Extraction fidelity: the committed `Evm` package is generated by the
  custom Sail compiler from the Sail model and validated byte-exact against
  EELS over the tests-zkevm v0.6.2 corpus (upstream CI). We verify against
  the generated Lean, not the Sail source.
* Crypto: `nativeAccelerateBytes` is `opaque` — unused by this tranche.
-/

namespace EvmSpecsVerify

/-- The fork constant the comparison is pinned to (`Evm` side numbering:
Amsterdam = 16, Primitives/Fork.lean). -/
abbrev pinnedFork : Nat := Evm.Functions.Amsterdam

end EvmSpecsVerify
